        !COMPILER-GENERATED INTERFACE MODULE: Sun Jan 28 17:56:05 2018
        MODULE PUNCH_GRID__genmod
          INTERFACE 
            SUBROUTINE PUNCH_GRID(PUNCH_FILE,NPT,XYZ,RHO)
              INTEGER(KIND=4), INTENT(IN) :: NPT
              CHARACTER(*), INTENT(IN) :: PUNCH_FILE
              REAL(KIND=8), INTENT(IN) :: XYZ(3,NPT)
              REAL(KIND=8), INTENT(IN) :: RHO(NPT)
            END SUBROUTINE PUNCH_GRID
          END INTERFACE 
        END MODULE PUNCH_GRID__genmod
