        !COMPILER-GENERATED INTERFACE MODULE: Sun Jan 28 17:56:05 2018
        MODULE READ_GRID__genmod
          INTERFACE 
            SUBROUTINE READ_GRID(GRID_FILE,XYZ,NPTS)
              CHARACTER(*), INTENT(IN) :: GRID_FILE
              REAL(KIND=8), INTENT(INOUT) :: XYZ(3,5000)
              INTEGER(KIND=4), INTENT(INOUT) :: NPTS
            END SUBROUTINE READ_GRID
          END INTERFACE 
        END MODULE READ_GRID__genmod
